package dev.rustybite.rustysosho.utils

data class CountryCode(
    val name: String,
    val code: String,
    val isoCode: String
)

val codes = listOf(
    CountryCode("Afghanistan", "+93", "AF"),
    CountryCode("Albania", "+355", "AL"),
    CountryCode("Algeria", "+213", "DZ"),
    CountryCode("American Samoa", "+1-684", "AS"),
    CountryCode("Andorra", "+376", "AD"),
    CountryCode("Angola", "+244", "AO"),
    CountryCode("Anguilla", "+1-264", "AI"),
    CountryCode("Antarctica", "+672", "AQ"),
    CountryCode("Antigua and Barbuda", "+1-268", "AG"),
    CountryCode("Argentina", "+54", "AR"),
    CountryCode("Armenia", "+374", "AM"),
    CountryCode("Aruba", "+297", "AW"),
    CountryCode("Australia", "+61", "AU"),
    CountryCode("Austria", "+43", "AT"),
    CountryCode("Azerbaijan", "+994", "AZ"),
    CountryCode("Bahamas", "+1-242", "BS"),
    CountryCode("Bahrain", "+973", "BH"),
    CountryCode("Bangladesh", "+880", "BD"),
    CountryCode("Barbados", "+1-246", "BD"),
    CountryCode("Belarus", "+375", "BY"),
    CountryCode("Belgium", "+32", "BE"),
    CountryCode("Belize", "+501", "BZ"),
    CountryCode("Benin", "+229", "BJ"),
    CountryCode("Bermuda", "+1-441", "BM"),
    CountryCode("Bhutan", "+975", "BT"),
    CountryCode("Bolivia", "+591", "BO"),
    CountryCode("Bosnia and Herzegovina", "+387", "BA"),
    CountryCode("Botswana", "+267", "BW"),
    CountryCode("Brazil", "+55", "BR"),
    CountryCode("British Indian Ocean Territory", "+246", "IO"),
    CountryCode("British Virgin Island", "+1-284", "VG"),
    CountryCode("Brunei", "+673", "BN"),
    CountryCode("Bulgaria", "+359", "BG"),
    CountryCode("Burkina Faso", "+226", "BF"),
    CountryCode("Burundi", "+257", "BI"),
    CountryCode("Cambodia", "+855", "KH"),
    CountryCode("Cameroon", "+237", "CM"),
    CountryCode("Brazil", "+55", "BR"),
    CountryCode("Canada", "+1", "CA"),
    CountryCode("Cape Verde", "+238", "CV"),
    CountryCode("Cayman Islands", "+1-345", "KY"),
    CountryCode("Central African Republic", "+236", "CF"),
    CountryCode("Chad", "+235", "TD"),
    CountryCode("Chile", "+56", "CL"),
    CountryCode("China", "+86", "CN"),
    CountryCode("Christmas Island", "+61", "CX"),
    CountryCode("Cocos Island", "+61", "CC"),
    CountryCode("Colombia", "+57", "CO"),
    CountryCode("Comoros", "+269", "KM"),
    CountryCode("Cook Island", "+682", "CK"),
    CountryCode("Costa Rica", "+506", "CR"),
    CountryCode("Croatia", "+385", "HR"),
    CountryCode("Cuba", "+53", "CU"),
    CountryCode("Curacao", "+599", "CW"),
    CountryCode("Cyprus", "+357", "CY"),
    CountryCode("Czech Republic", "+420", "CZ"),
    CountryCode("DR Congo", "+243", "CD"),
    CountryCode("Denmark", "+45", "DK"),
    CountryCode("Djibouti", "+253", "DJ"),
    CountryCode("Dominica", "+1-767", "DM"),
    CountryCode("East Timor", "+670", "TL"),
    CountryCode("Ecuador", "+593", "EC"),
    CountryCode("Egypt", "+20", "EG"),
    CountryCode("El Salvador", "+503", "SV"),
    CountryCode("Equatorial Guinea", "+240", "GQ"),
    CountryCode("Eritrea", "+291", "ER"),
    CountryCode("Estonia", "+372", "EE"),
    CountryCode("Ethiopia", "+251", "ET"),
    CountryCode("Falkland Island", "+500", "FK"),
    CountryCode("Faroe Island", "+298", "FO"),
    CountryCode("Fiji", "+679", "FJ"),
    CountryCode("Finland", "+358", "FI"),
    CountryCode("France", "+33", "FR"),
    CountryCode("French Polynesia", "+689", "PF"),
    CountryCode("Gabon", "+241", "GA"),
    CountryCode("Gambia", "+220", "GM"),
    CountryCode("Georgia", "+995", "GE"),
    CountryCode("German", "+49", "DE"),
    CountryCode("Ghana", "+233", "GH"),
    CountryCode("Gibraltar", "+350", "GI"),
    CountryCode("Greece", "+30", "GR"),
    CountryCode("Greenland", "+299", "GL"),
    CountryCode("Grenada", "+1-473", "GD"),
    CountryCode("Guam", "+1-671", "GU"),
    CountryCode("Guatemala", "+502", "GT"),
    CountryCode("Guernsey", "+44-1481", "GI"),
    CountryCode("Guinea", "+224", "GN"),
    CountryCode("Guinea-Bissau", "+245", "GW"),
    CountryCode("Guyana", "+592", "GY"),
    CountryCode("Haiti", "+509", "HT"),
    CountryCode("Honduras", "+504", "HN"),
    CountryCode("Hong Kong", "+852", "HK"),
    CountryCode("Hungary", "+36", "HU"),
    CountryCode("Iceland", "+354", "IS"),
    CountryCode("India", "+91", "IN"),
    CountryCode("Indonesia", "+62", "ID"),
    CountryCode("Iran", "+98", "IR"),
    CountryCode("Iraq", "+964", "IQ"),
    CountryCode("Ireland", "+353", "IE"),
    CountryCode("Isle of Man", "+44-1624", "IM"),
    CountryCode("Israel", "+353", "IL"),
    CountryCode("Italy", "+39", "IT"),
    CountryCode("Ivory Coast", "+225", "CI"),
    CountryCode("Jamaica", "+1-876", "JM"),
    CountryCode("Japan", "+81", "JP"),
    CountryCode("Jersey", "+44-1534", "JE"),
    CountryCode("Jordan", "+962", "JO"),
    CountryCode("Kazakhstan", "+7", "KZ"),
    CountryCode("Kenya", "+254", "KE"),
    CountryCode("Kiribati", "+686", "KI"),
    CountryCode("Kosovo", "+383", "XK"),
    CountryCode("Kuwait", "+965", "KW"),
    CountryCode("Kyrgyzstan", "+996", "KG"),
    CountryCode("Laos", "+856", "LA"),
    CountryCode("Latvia", "+371", "LV"),
    CountryCode("Lebanon", "+961", "LB"),
    CountryCode("Lesotho", "+266", "LS"),
    CountryCode("Liberia", "+231", "LR"),
    CountryCode("Libya", "+218", "LY"),
    CountryCode("Liechtenstein", "+423", "LI"),
    CountryCode("Lithuania", "+730", "LT"),
    CountryCode("Luxembourg", "+352", "LU"),
    CountryCode("Macau", "+853", "MO"),
    CountryCode("Macedonia", "+389", "MK"),
    CountryCode("Madagascar", "+261", "MG"),
    CountryCode("Malawi", "+265", "MW"),
    CountryCode("Malaysia", "+60", "MO"),
    CountryCode("Maldives", "+960", "MV"),
    CountryCode("Mali", "+223", "ML"),
    CountryCode("Malta", "+356", "MT"),
    CountryCode("Marshall Islands", "+692", "MH"),
    CountryCode("Mauritania", "+222", "MR"),
    CountryCode("Mauritius", "+230", "MO"),
    CountryCode("Mayotte", "+262", "YT"),
    CountryCode("Mexico", "+52", "MX"),
    CountryCode("Micronesia", "+691", "FM"),
    CountryCode("Moldova", "+373", "MD"),
    CountryCode("Monaco", "+377", "MC"),
    CountryCode("Mongolia", "+976", "MN"),
    CountryCode("Montenegro", "+382", "ME"),
    CountryCode("Montserrat", "+1-664", "MS"),
    CountryCode("Morocco", "+212", "MA"),
    CountryCode("Mozambique", "+258", "MZ"),
    CountryCode("Myanmar", "+95", "MM"),
    CountryCode("Namibia", "+264", "NA"),
    CountryCode("Nauru", "+674", "NR"),
    CountryCode("Nepal", "+977", "NP"),
    CountryCode("Netherlands", "+31", "NL"),
    CountryCode("Netherlands Antilles", "+599", "AN"),
    CountryCode("New Caledonia", "+687", "NC"),
    CountryCode("New Zealand", "+64", "NZ"),
    CountryCode("Nicaragua", "+505", "NI"),
    CountryCode("Niger", "+227", "NE"),
    CountryCode("Nigeria", "+234", "NG"),
    CountryCode("Niue", "+683", "NU"),
    CountryCode("North Korea", "+850", "KP"),
    CountryCode("Northern Mariana Islands", "+1-670", "MP"),
    CountryCode("Norway", "+47", "NO"),
    CountryCode("Oman", "+968", "OM"),
    CountryCode("Pakistan", "+92", "PK"),
    CountryCode("Palau", "+680", "PW"),
    CountryCode("Palestine", "+970", "PS"),
    CountryCode("Panama", "+507", "PA"),
    CountryCode("Papua New Guinea", "+675", "PG"),
    CountryCode("Paraguay", "+595", "PY"),
    CountryCode("Peru", "+51", "PE"),
    CountryCode("Philippines", "+63", "PH"),
    CountryCode("Pitcairn", "+64", "PN"),
    CountryCode("Poland", "+48", "PL"),
    CountryCode("Portugal", "+351", "PT"),
    CountryCode("Puerto Rico", "+1-787", "PR"),
    CountryCode("Qatar", "+974", "QA"),
    CountryCode("Qatar", "+974", "QA"),
    CountryCode("Reunion", "+262", "RE"),
    CountryCode("Romania", "+40", "RO"),
    CountryCode("Russia", "+7", "RU"),
    CountryCode("Rwanda", "+250", "RW"),
    CountryCode("Saint Barthelemy", "+590", "BL"),
    CountryCode("Saint Helena", "+290", "SH"),
    CountryCode("Saint Kitts and Nevis", "+1-869", "QA"),
    CountryCode("Saint Lucia", "+1-758", "LC"),
    CountryCode("Saint Martin", "+590", "MF"),
    CountryCode("Saint Pierre and Miquelon", "+508", "PM"),
    CountryCode("Saint Vincent and the Grenadines", "+1-784", "VC"),
    CountryCode("Samoa", "+685", "WS"),
    CountryCode("San Marino", "+378", "SM"),
    CountryCode("Sao Tome and Principe", "+239", "ST"),
    CountryCode("Saudi Arabia", "+966", "SA"),
    CountryCode("Senegal", "+221", "SN"),
    CountryCode("Serbia", "+381", "RS"),
    CountryCode("Seychelles", "+248", "SC"),
    CountryCode("Sierra Leone", "+232", "SL"),
    CountryCode("Singapore", "+65", "SG"),
    CountryCode("Sint Maarten", "+1-721", "WS"),
    CountryCode("Slovakia", "+421", "SK"),
    CountryCode("Slovenia", "+386", "SI"),
    CountryCode("Solomon Islands", "+677", "SB"),
    CountryCode("Somalia", "+252", "SO"),
    CountryCode("South Africa", "+27", "ZA"),
    CountryCode("South Korea", "+82", "KR"),
    CountryCode("South Sudan", "+211", "SS"),
    CountryCode("Spain", "+34", "ES"),
    CountryCode("Sri Lanka", "+94", "LK"),
    CountryCode("Sudan", "+249", "SD"),
    CountryCode("Suriname", "+597", "SR"),
    CountryCode("Svalbard and Jan Mayen", "+47", "SJ"),
    CountryCode("Swaziland", "+268", "SZ"),
    CountryCode("Sweden", "+46", "SE"),
    CountryCode("Switzerland", "+41", "CH"),
    CountryCode("Syria", "+963", "SY"),
    CountryCode("Taiwan", "+886", "TW"),
    CountryCode("Tajikistan", "+992", "TJ"),
    CountryCode("Tanzania", "+255", "TZ"),
    CountryCode("Thailand", "+66", "TH"),
    CountryCode("Togo", "+228", "TG"),
    CountryCode("Tokelau", "+690", "TK"),
    CountryCode("Tonga", "+676", "TO"),
    CountryCode("Trinidad and Tobago", "+1-868", "TT"),
    CountryCode("Tunisia", "+216", "TN"),
    CountryCode("Turkey", "+90", "TR"),
    CountryCode("Turkmenistan", "+993", "TM"),
    CountryCode("Turks and Caicos Island", "+1-649", "TC"),
    CountryCode("Tuvalu", "+688", "TV"),
    CountryCode("U.S. Virgin Islands", "+1-340", "TW"),
    CountryCode("Uganda", "+256", "UG"),
    CountryCode("United Arab Emirates", "+971", "AE"),
    CountryCode("United Kingdom", "+44", "GB"),
    CountryCode("United States", "+1", "US"),
    CountryCode("Uruguay", "+598", "UY"),
    CountryCode("Uzbekistan", "+998", "UZ"),
    CountryCode("Vanuatu", "+687", "VU"),
    CountryCode("Vatican", "+379", "VA"),
    CountryCode("Venezuela", "+58", "VE"),
    CountryCode("Vietnam", "+84", "VN"),
    CountryCode("Wallis and Futuna", "+681", "WF"),
    CountryCode("Western Sahara", "+212", "EH"),
    CountryCode("Yemen", "+967", "YE"),
    CountryCode("Zambia", "+260", "ZM"),
    CountryCode("Zimbabwe", "+263", "ZW"),
)